version: '3'

services:
    backend:
        container_name: graphql_backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - mongo_server
        volumes:
            - .:/backend
        working_dir: /backend
        command: tail -f /dev/null

    mongo_server:
        container_name: graphql_mongo
        image: mongo:3.4.9
        ports:
            - "27017:27017"
